config:
  credentials: []
  project_repos:
    github.com/Deltares/hydromt_wflow:
      branch: main
      repo: https://github.com/Deltares/hydromt_wflow
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Deltares/hydromt_wflow git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-brown-tarsier.sh
        container: qc.acc_wiggy-chocolate-cat
  QC.Doc:
    repos:
      github.com/Deltares/hydromt_wflow find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-wisteria-gharial.sh
        container: qc.doc_muzzy-copper-yak
      github.com/Deltares/hydromt_wflow git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-coral-affenpinscher.sh
        container: qc.doc_flimsy-champagne-frog
      github.com/Deltares/hydromt_wflow markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-goldenrod-dachshund.sh
        container: qc.doc_silly-asparagus-vulture
      github.com/Deltares/hydromt_wflow restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-ochre-kakapo.sh
        container: qc.doc_geeky-aquamarine-giraffe
  QC.Lic:
    repos:
      github.com/Deltares/hydromt_wflow licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-persimmon-collie.sh
        container: qc.lic_pasty-wheat-fossa
  QC.Sec:
    repos:
      github.com/Deltares/hydromt_wflow bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-chestnut-woodlouse.sh
        container: qc.sec_flaky-indigo-ant
  QC.Sty:
    repos:
      github.com/Deltares/hydromt_wflow flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-fuchsia-numbat.sh
        container: qc.sty_skanky-sangria-moose
      github.com/Deltares/hydromt_wflow jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-olive-capybara.sh
        container: qc.sty_pasty-salmon-macaw
  QC.Uni:
    repos:
      github.com/Deltares/hydromt_wflow pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-razzmatazz-weasel.sh
        container: qc.uni_clammy-scarlet-coyote
  QC.Ver:
    repos:
      github.com/Deltares/hydromt_wflow get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-purple-mastiff.sh
        container: qc.ver_silly-azure-beagle
timeout: 5400
